// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Server_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Server_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Server_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Server_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Server_2eproto;
namespace ServerProto {
class ServerInfo;
struct ServerInfoDefaultTypeInternal;
extern ServerInfoDefaultTypeInternal _ServerInfo_default_instance_;
class UserInfo;
struct UserInfoDefaultTypeInternal;
extern UserInfoDefaultTypeInternal _UserInfo_default_instance_;
}  // namespace ServerProto
PROTOBUF_NAMESPACE_OPEN
template<> ::ServerProto::ServerInfo* Arena::CreateMaybeMessage<::ServerProto::ServerInfo>(Arena*);
template<> ::ServerProto::UserInfo* Arena::CreateMaybeMessage<::ServerProto::UserInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ServerProto {

enum ServerInfo_Operation : int {
  ServerInfo_Operation_Register = 0,
  ServerInfo_Operation_RequstAssgin = 1,
  ServerInfo_Operation_Connect = 2,
  ServerInfo_Operation_ServerInfo_Operation_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ServerInfo_Operation_ServerInfo_Operation_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ServerInfo_Operation_IsValid(int value);
constexpr ServerInfo_Operation ServerInfo_Operation_Operation_MIN = ServerInfo_Operation_Register;
constexpr ServerInfo_Operation ServerInfo_Operation_Operation_MAX = ServerInfo_Operation_Connect;
constexpr int ServerInfo_Operation_Operation_ARRAYSIZE = ServerInfo_Operation_Operation_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ServerInfo_Operation_descriptor();
template<typename T>
inline const std::string& ServerInfo_Operation_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ServerInfo_Operation>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ServerInfo_Operation_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ServerInfo_Operation_descriptor(), enum_t_value);
}
inline bool ServerInfo_Operation_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ServerInfo_Operation* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ServerInfo_Operation>(
    ServerInfo_Operation_descriptor(), name, value);
}
enum UserInfo_Operation : int {
  UserInfo_Operation_Register = 0,
  UserInfo_Operation_Logout = 1,
  UserInfo_Operation_UserInfo_Operation_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  UserInfo_Operation_UserInfo_Operation_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool UserInfo_Operation_IsValid(int value);
constexpr UserInfo_Operation UserInfo_Operation_Operation_MIN = UserInfo_Operation_Register;
constexpr UserInfo_Operation UserInfo_Operation_Operation_MAX = UserInfo_Operation_Logout;
constexpr int UserInfo_Operation_Operation_ARRAYSIZE = UserInfo_Operation_Operation_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UserInfo_Operation_descriptor();
template<typename T>
inline const std::string& UserInfo_Operation_Name(T enum_t_value) {
  static_assert(::std::is_same<T, UserInfo_Operation>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function UserInfo_Operation_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    UserInfo_Operation_descriptor(), enum_t_value);
}
inline bool UserInfo_Operation_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, UserInfo_Operation* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<UserInfo_Operation>(
    UserInfo_Operation_descriptor(), name, value);
}
// ===================================================================

class ServerInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ServerProto.ServerInfo) */ {
 public:
  inline ServerInfo() : ServerInfo(nullptr) {}
  ~ServerInfo() override;
  explicit constexpr ServerInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerInfo(const ServerInfo& from);
  ServerInfo(ServerInfo&& from) noexcept
    : ServerInfo() {
    *this = ::std::move(from);
  }

  inline ServerInfo& operator=(const ServerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerInfo& operator=(ServerInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerInfo* internal_default_instance() {
    return reinterpret_cast<const ServerInfo*>(
               &_ServerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerInfo& a, ServerInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServerInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ServerInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ServerProto.ServerInfo";
  }
  protected:
  explicit ServerInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ServerInfo_Operation Operation;
  static constexpr Operation Register =
    ServerInfo_Operation_Register;
  static constexpr Operation RequstAssgin =
    ServerInfo_Operation_RequstAssgin;
  static constexpr Operation Connect =
    ServerInfo_Operation_Connect;
  static inline bool Operation_IsValid(int value) {
    return ServerInfo_Operation_IsValid(value);
  }
  static constexpr Operation Operation_MIN =
    ServerInfo_Operation_Operation_MIN;
  static constexpr Operation Operation_MAX =
    ServerInfo_Operation_Operation_MAX;
  static constexpr int Operation_ARRAYSIZE =
    ServerInfo_Operation_Operation_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Operation_descriptor() {
    return ServerInfo_Operation_descriptor();
  }
  template<typename T>
  static inline const std::string& Operation_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Operation>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Operation_Name.");
    return ServerInfo_Operation_Name(enum_t_value);
  }
  static inline bool Operation_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Operation* value) {
    return ServerInfo_Operation_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 1,
    kPortFieldNumber = 2,
    kServerFreeLevelFieldNumber = 3,
    kServerTypeFieldNumber = 4,
    kOptFieldNumber = 5,
  };
  // string ip = 1;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // int32 port = 2;
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // int32 server_free_level = 3;
  void clear_server_free_level();
  int32_t server_free_level() const;
  void set_server_free_level(int32_t value);
  private:
  int32_t _internal_server_free_level() const;
  void _internal_set_server_free_level(int32_t value);
  public:

  // int32 server_type = 4;
  void clear_server_type();
  int32_t server_type() const;
  void set_server_type(int32_t value);
  private:
  int32_t _internal_server_type() const;
  void _internal_set_server_type(int32_t value);
  public:

  // .ServerProto.ServerInfo.Operation opt = 5;
  void clear_opt();
  ::ServerProto::ServerInfo_Operation opt() const;
  void set_opt(::ServerProto::ServerInfo_Operation value);
  private:
  ::ServerProto::ServerInfo_Operation _internal_opt() const;
  void _internal_set_opt(::ServerProto::ServerInfo_Operation value);
  public:

  // @@protoc_insertion_point(class_scope:ServerProto.ServerInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
  int32_t port_;
  int32_t server_free_level_;
  int32_t server_type_;
  int opt_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Server_2eproto;
};
// -------------------------------------------------------------------

class UserInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ServerProto.UserInfo) */ {
 public:
  inline UserInfo() : UserInfo(nullptr) {}
  ~UserInfo() override;
  explicit constexpr UserInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UserInfo(const UserInfo& from);
  UserInfo(UserInfo&& from) noexcept
    : UserInfo() {
    *this = ::std::move(from);
  }

  inline UserInfo& operator=(const UserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserInfo& operator=(UserInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserInfo* internal_default_instance() {
    return reinterpret_cast<const UserInfo*>(
               &_UserInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UserInfo& a, UserInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(UserInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UserInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UserInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const UserInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ServerProto.UserInfo";
  }
  protected:
  explicit UserInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef UserInfo_Operation Operation;
  static constexpr Operation Register =
    UserInfo_Operation_Register;
  static constexpr Operation Logout =
    UserInfo_Operation_Logout;
  static inline bool Operation_IsValid(int value) {
    return UserInfo_Operation_IsValid(value);
  }
  static constexpr Operation Operation_MIN =
    UserInfo_Operation_Operation_MIN;
  static constexpr Operation Operation_MAX =
    UserInfo_Operation_Operation_MAX;
  static constexpr int Operation_ARRAYSIZE =
    UserInfo_Operation_Operation_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Operation_descriptor() {
    return UserInfo_Operation_descriptor();
  }
  template<typename T>
  static inline const std::string& Operation_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Operation>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Operation_Name.");
    return UserInfo_Operation_Name(enum_t_value);
  }
  static inline bool Operation_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Operation* value) {
    return UserInfo_Operation_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kUseridFieldNumber = 1,
    kFdFieldNumber = 2,
    kOptFieldNumber = 3,
  };
  // string userid = 1;
  void clear_userid();
  const std::string& userid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_userid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_userid();
  PROTOBUF_NODISCARD std::string* release_userid();
  void set_allocated_userid(std::string* userid);
  private:
  const std::string& _internal_userid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_userid(const std::string& value);
  std::string* _internal_mutable_userid();
  public:

  // int32 fd = 2;
  void clear_fd();
  int32_t fd() const;
  void set_fd(int32_t value);
  private:
  int32_t _internal_fd() const;
  void _internal_set_fd(int32_t value);
  public:

  // .ServerProto.UserInfo.Operation opt = 3;
  void clear_opt();
  ::ServerProto::UserInfo_Operation opt() const;
  void set_opt(::ServerProto::UserInfo_Operation value);
  private:
  ::ServerProto::UserInfo_Operation _internal_opt() const;
  void _internal_set_opt(::ServerProto::UserInfo_Operation value);
  public:

  // @@protoc_insertion_point(class_scope:ServerProto.UserInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr userid_;
  int32_t fd_;
  int opt_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Server_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerInfo

// string ip = 1;
inline void ServerInfo::clear_ip() {
  ip_.ClearToEmpty();
}
inline const std::string& ServerInfo::ip() const {
  // @@protoc_insertion_point(field_get:ServerProto.ServerInfo.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerInfo::set_ip(ArgT0&& arg0, ArgT... args) {
 
 ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ServerProto.ServerInfo.ip)
}
inline std::string* ServerInfo::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:ServerProto.ServerInfo.ip)
  return _s;
}
inline const std::string& ServerInfo::_internal_ip() const {
  return ip_.Get();
}
inline void ServerInfo::_internal_set_ip(const std::string& value) {
  
  ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ServerInfo::_internal_mutable_ip() {
  
  return ip_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ServerInfo::release_ip() {
  // @@protoc_insertion_point(field_release:ServerProto.ServerInfo.ip)
  return ip_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ServerInfo::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  ip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ip_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ServerProto.ServerInfo.ip)
}

// int32 port = 2;
inline void ServerInfo::clear_port() {
  port_ = 0;
}
inline int32_t ServerInfo::_internal_port() const {
  return port_;
}
inline int32_t ServerInfo::port() const {
  // @@protoc_insertion_point(field_get:ServerProto.ServerInfo.port)
  return _internal_port();
}
inline void ServerInfo::_internal_set_port(int32_t value) {
  
  port_ = value;
}
inline void ServerInfo::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:ServerProto.ServerInfo.port)
}

// int32 server_free_level = 3;
inline void ServerInfo::clear_server_free_level() {
  server_free_level_ = 0;
}
inline int32_t ServerInfo::_internal_server_free_level() const {
  return server_free_level_;
}
inline int32_t ServerInfo::server_free_level() const {
  // @@protoc_insertion_point(field_get:ServerProto.ServerInfo.server_free_level)
  return _internal_server_free_level();
}
inline void ServerInfo::_internal_set_server_free_level(int32_t value) {
  
  server_free_level_ = value;
}
inline void ServerInfo::set_server_free_level(int32_t value) {
  _internal_set_server_free_level(value);
  // @@protoc_insertion_point(field_set:ServerProto.ServerInfo.server_free_level)
}

// int32 server_type = 4;
inline void ServerInfo::clear_server_type() {
  server_type_ = 0;
}
inline int32_t ServerInfo::_internal_server_type() const {
  return server_type_;
}
inline int32_t ServerInfo::server_type() const {
  // @@protoc_insertion_point(field_get:ServerProto.ServerInfo.server_type)
  return _internal_server_type();
}
inline void ServerInfo::_internal_set_server_type(int32_t value) {
  
  server_type_ = value;
}
inline void ServerInfo::set_server_type(int32_t value) {
  _internal_set_server_type(value);
  // @@protoc_insertion_point(field_set:ServerProto.ServerInfo.server_type)
}

// .ServerProto.ServerInfo.Operation opt = 5;
inline void ServerInfo::clear_opt() {
  opt_ = 0;
}
inline ::ServerProto::ServerInfo_Operation ServerInfo::_internal_opt() const {
  return static_cast< ::ServerProto::ServerInfo_Operation >(opt_);
}
inline ::ServerProto::ServerInfo_Operation ServerInfo::opt() const {
  // @@protoc_insertion_point(field_get:ServerProto.ServerInfo.opt)
  return _internal_opt();
}
inline void ServerInfo::_internal_set_opt(::ServerProto::ServerInfo_Operation value) {
  
  opt_ = value;
}
inline void ServerInfo::set_opt(::ServerProto::ServerInfo_Operation value) {
  _internal_set_opt(value);
  // @@protoc_insertion_point(field_set:ServerProto.ServerInfo.opt)
}

// -------------------------------------------------------------------

// UserInfo

// string userid = 1;
inline void UserInfo::clear_userid() {
  userid_.ClearToEmpty();
}
inline const std::string& UserInfo::userid() const {
  // @@protoc_insertion_point(field_get:ServerProto.UserInfo.userid)
  return _internal_userid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UserInfo::set_userid(ArgT0&& arg0, ArgT... args) {
 
 userid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ServerProto.UserInfo.userid)
}
inline std::string* UserInfo::mutable_userid() {
  std::string* _s = _internal_mutable_userid();
  // @@protoc_insertion_point(field_mutable:ServerProto.UserInfo.userid)
  return _s;
}
inline const std::string& UserInfo::_internal_userid() const {
  return userid_.Get();
}
inline void UserInfo::_internal_set_userid(const std::string& value) {
  
  userid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* UserInfo::_internal_mutable_userid() {
  
  return userid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* UserInfo::release_userid() {
  // @@protoc_insertion_point(field_release:ServerProto.UserInfo.userid)
  return userid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void UserInfo::set_allocated_userid(std::string* userid) {
  if (userid != nullptr) {
    
  } else {
    
  }
  userid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), userid,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (userid_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    userid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ServerProto.UserInfo.userid)
}

// int32 fd = 2;
inline void UserInfo::clear_fd() {
  fd_ = 0;
}
inline int32_t UserInfo::_internal_fd() const {
  return fd_;
}
inline int32_t UserInfo::fd() const {
  // @@protoc_insertion_point(field_get:ServerProto.UserInfo.fd)
  return _internal_fd();
}
inline void UserInfo::_internal_set_fd(int32_t value) {
  
  fd_ = value;
}
inline void UserInfo::set_fd(int32_t value) {
  _internal_set_fd(value);
  // @@protoc_insertion_point(field_set:ServerProto.UserInfo.fd)
}

// .ServerProto.UserInfo.Operation opt = 3;
inline void UserInfo::clear_opt() {
  opt_ = 0;
}
inline ::ServerProto::UserInfo_Operation UserInfo::_internal_opt() const {
  return static_cast< ::ServerProto::UserInfo_Operation >(opt_);
}
inline ::ServerProto::UserInfo_Operation UserInfo::opt() const {
  // @@protoc_insertion_point(field_get:ServerProto.UserInfo.opt)
  return _internal_opt();
}
inline void UserInfo::_internal_set_opt(::ServerProto::UserInfo_Operation value) {
  
  opt_ = value;
}
inline void UserInfo::set_opt(::ServerProto::UserInfo_Operation value) {
  _internal_set_opt(value);
  // @@protoc_insertion_point(field_set:ServerProto.UserInfo.opt)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerProto

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ServerProto::ServerInfo_Operation> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ServerProto::ServerInfo_Operation>() {
  return ::ServerProto::ServerInfo_Operation_descriptor();
}
template <> struct is_proto_enum< ::ServerProto::UserInfo_Operation> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ServerProto::UserInfo_Operation>() {
  return ::ServerProto::UserInfo_Operation_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Server_2eproto
